
CREATE TABLE room (
                       id VARCHAR(255) NOT NULL,
                       name VARCHAR(255) NOT NULL,
                       owner_id BIGINT,
                       owner_display_name VARCHAR(255),
                       map_index INTEGER DEFAULT 0,
                       status VARCHAR(50),
                       created TIMESTAMP WITHOUT TIME ZONE,
                       max_players INTEGER DEFAULT 4,
                       CONSTRAINT pk_rooms PRIMARY KEY (id)
);

CREATE TABLE player_slot (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              room_id VARCHAR(255) NOT NULL,

                              slot_index INTEGER NOT NULL,
                              occupied BOOLEAN DEFAULT FALSE,
                              is_bot BOOLEAN DEFAULT FALSE,
                              user_id BIGINT,
                              display_name VARCHAR(255),
                              is_host BOOLEAN DEFAULT FALSE,
                              is_ready BOOLEAN DEFAULT FALSE,
                              character_index INTEGER DEFAULT 0,

                              CONSTRAINT pk_player_slot PRIMARY KEY (id),
                              CONSTRAINT fk_slot_room FOREIGN KEY (room_id) REFERENCES room(id) ON DELETE CASCADE
);


CREATE TABLE chat_message (
                               id VARCHAR(255) NOT NULL,
                               room_id VARCHAR(255) NOT NULL,

                               type VARCHAR(50),
                               sender_id BIGINT,
                               sender_display_name VARCHAR(255),
                               content TEXT,
                               created TIMESTAMP WITHOUT TIME ZONE,

                               CONSTRAINT pk_chat_message PRIMARY KEY (id),
                               CONSTRAINT fk_chat_room FOREIGN KEY (room_id) REFERENCES room(id) ON DELETE CASCADE
);